### ISSUE TITLE
Home page has some elements that are not refreshed

### ISSUE THREAD

**Issue by marcgemis** [openstreetcam/openstreetview.org#47] opened 2016-08-12 05:04 UTC
For some reason not all elements on my home page are refreshed properly (I think)
- There is a broken image for the single trace that I uploaded via the app
- 3 other traces are still processing after a couple of days.

![screenshot](https://photos.smugmug.com/OSM/Screenshots/Screenshots-1/i-TbjswSX/0/X3/OpenStreetView-X3.png)

**Comment by james2432** [comment] 2016-08-12 10:09
The processing part is normal if there were a lot of people uploading images this week(hint there was)

For the other problem it's a duplicate of #10

**Closed** 2018-02-04 11:41 UTC
